[window]
opacity = 0.95
decorations = "none"  # Remove title bar
padding = { x = 5, y = 5 }

[colors.primary]
background = "#1e1e2e"  # Catppuccin/Nord background
foreground = "#cdd6f4"  # Default text color

[terminal]

[terminal.shell]
program = "/usr/bin/tmux"
